import type { StoryFragmentDefinition, TimeNodeDefinition } from './model'

// Source: Epic_Fragment_GDD_v0.1.3, chapters 10–11. Evidence describes
// what a source claims; these definitions never certify historical truth.
export const demoTimeNodes: readonly TimeNodeDefinition[] = [
  { id: 'T0', label: '先王晚年朝政异常', result: '先王晚年不再亲自处理大部分朝政。' },
  { id: 'T1', label: '国王死亡', result: '王城收到国王死亡的消息。' },
  { id: 'T2', label: '首相发布命令', result: '一份要求释放囚犯的命令传入监狱。' },
  { id: 'T3', label: '监狱拒绝执行', result: '监狱没有按释放令放人。' },
  { id: 'T4', label: '城外军队调动', result: '王城周围出现军队调动。' },
  { id: 'T5', label: '王城混乱', result: '王城秩序陷入混乱。' },
]

export const demoFragments: readonly StoryFragmentDefinition[] = [
  {
    id: 'F01', timeNodeId: 'T0', title: '晚年政务记录',
    statement: '先王晚年不理朝政，政务全交首相。',
    source: '监狱档案中的官方记录', sourceType: 'officialRecord', faction: '王室',
    reliabilityHint: '这是一份官方记录，未记下国王本人的说法。', supportsStorylines: ['coup', 'loyalist'],
    characters: ['先王', '首相'], locations: ['监狱档案室'], relatedFragments: [],
    tags: ['王权', '首相'], narrativeText: '官方记录称，先王晚年将政务交给首相。',
  },
  {
    id: 'F02', timeNodeId: 'T0', title: '侍从日记',
    statement: '先王晚年常与弄臣独处，不许旁人靠近。',
    source: '王室廊道画像背面的私人日记', sourceType: 'privateJournal',
    reliabilityHint: '侍从记录的是自己所见，未说明国王与弄臣谈了什么。',
    characters: ['先王', '弄臣'], locations: ['皇宫王室廊道'], relatedFragments: ['F01', 'F11'],
    tags: ['先王', '弄臣'], narrativeText: '一名侍从写道，先王晚年常与弄臣独处。',
  },
  {
    id: 'F03', timeNodeId: 'T1', title: '国王死讯公告',
    statement: '国王已死。',
    source: '祭坛中镶嵌的官方公告', sourceType: 'officialNotice', faction: '王室',
    reliabilityHint: '公告只确认死讯，没有说明死因。', conflictGroup: 'CG_T1', supportsStorylines: ['coup'],
    characters: ['国王'], locations: ['监狱祭坛'], relatedFragments: ['F04'],
    tags: ['死讯'], narrativeText: '一份官方公告称，国王已经死亡；死因未写明。',
  },
  {
    id: 'F04', timeNodeId: 'T1', title: '卧病记录',
    statement: '国王晚年卧病三月，药石罔效。',
    source: '私人日记', sourceType: 'privateJournal',
    reliabilityHint: '私人记录可能只看到病情的一部分。', conflictGroup: 'CG_T1', supportsStorylines: ['loyalist'],
    characters: ['国王'], locations: ['皇宫书房'], relatedFragments: ['F03'],
    tags: ['病情'], narrativeText: '一份私人日记记下国王卧病三月，药石罔效。',
  },
  {
    id: 'F15', timeNodeId: 'T1', title: '遗体暗色痕迹',
    statement: '国王遗体嘴角有暗色痕迹，御医记录为久病体虚。',
    source: '国王卧室的遗体验尸记录', sourceType: 'forensicRecord',
    reliabilityHint: '痕迹与御医记录不一致，但尚不足以确认死因。', conflictGroup: 'CG_T1',
    characters: ['国王', '御医'], locations: ['皇宫国王卧室'], relatedFragments: ['F03', 'F04'],
    tags: ['遗体', '死因'], narrativeText: '调查者发现遗体嘴角有暗色痕迹，御医记录却写着久病体虚。',
    supportsStorylines: ['coup'],
  },
  {
    id: 'F05', timeNodeId: 'T2', title: '释放囚犯手令',
    statement: '首相手令：释放所有囚犯，入宫勤王。',
    source: '责难官持有的官方文件', sourceType: 'officialRecord', faction: '首相',
    reliabilityHint: '手令署名首相，其传递经过仍待调查。', supportsStorylines: ['coup', 'loyalist'],
    characters: ['首相', '责难官'], locations: ['监狱刑讯室'], relatedFragments: ['F06', 'F07'],
    tags: ['释放令', '勤王'], narrativeText: '一份署名首相的手令要求释放囚犯入宫勤王。',
  },
  {
    id: 'F06', timeNodeId: 'T2', title: '手令印章异样',
    statement: '首相手令的印章与以往文件略有不同。',
    source: '皇宫地下通道的信件与物品观察', sourceType: 'object',
    reliabilityHint: '印章不同可能有多种解释，尚不能确认是谁改动。', conflictGroup: 'CG_T2',
    characters: ['首相'], locations: ['皇宫地下通道'], relatedFragments: ['F05'],
    tags: ['印章', '命令'], narrativeText: '另一份线索指出，手令印章与以往文件略有不同。',
  },
  {
    id: 'F07', timeNodeId: 'T3', title: '典狱长拒令公告',
    statement: '典狱长拒绝执行释放令，称无典狱长手谕不得放人。',
    source: '监狱大厅公告板', sourceType: 'officialNotice', faction: '监狱',
    reliabilityHint: '公告记下拒绝执行的结果，没有解释典狱长的动机。', conflictGroup: 'CG_T3', supportsStorylines: ['coup'],
    characters: ['典狱长'], locations: ['监狱大厅'], relatedFragments: ['F05', 'F08'],
    tags: ['拒令'], narrativeText: '监狱公告记载，典狱长拒绝执行释放令。',
  },
  {
    id: 'F08', timeNodeId: 'T3', title: '典狱长与三王子',
    statement: '典狱长深夜与三王子的密使会面。',
    source: '皇宫塔楼顶部尸体上的私人记录', sourceType: 'privateJournal',
    conflictGroup: 'CG_T3', supportsStorylines: ['loyalist'], characters: ['典狱长', '三王子密使'], locations: ['皇宫塔楼顶部'],
    relatedFragments: ['F07'], tags: ['密会'],
    narrativeText: '一份私人记录称，典狱长深夜曾与三王子的密使会面。',
  },
  {
    id: 'F09', timeNodeId: 'T4', title: '狮心军集结',
    statement: '狮心军在城外三十里处集结。',
    source: '皇宫塔楼顶部的远景观察记录', sourceType: 'environment',
    conflictGroup: 'CG_T4', supportsStorylines: ['loyalist'], characters: ['狮心军'], locations: ['皇宫塔楼顶部', '王城外'],
    relatedFragments: ['F10'], tags: ['军队'],
    narrativeText: '塔楼的观察记录称，城外三十里处有狮心军集结。',
  },
  {
    id: 'F10', timeNodeId: 'T4', title: '城门封锁令',
    statement: '禁卫封锁了所有城门，出入需首相手令。',
    source: '皇宫前厅禁卫队长尸体上的官方命令', sourceType: 'officialRecord', faction: '首相',
    conflictGroup: 'CG_T4', supportsStorylines: ['coup'], characters: ['首相', '禁卫'], locations: ['皇宫前厅'],
    relatedFragments: ['F09'], tags: ['军队', '城门'],
    narrativeText: '一份命令记载，禁卫封锁城门，出入需首相手令。',
  },
  {
    id: 'F11', timeNodeId: 'T5', title: '弄臣遗言',
    statement: '三王子等不及了。',
    source: '弄臣的记忆', sourceType: 'bossMemory',
    reliabilityHint: '这是弄臣临终的说法，所指的行动尚不明确。',
    characters: ['弄臣', '三王子'], locations: ['皇宫国王卧室'], relatedFragments: ['F02'],
    tags: ['王城混乱'], narrativeText: '弄臣的遗言提到，三王子等不及了。',
  },
  {
    id: 'F12', timeNodeId: 'T5', title: '潜入王城的刺客',
    statement: '奴隶军刺客已经潜入城中。',
    source: '典狱长持有的敌方文件', sourceType: 'hostileDocument',
    reliabilityHint: '文件记录了潜入计划，尚需确认执行情况。',
    characters: ['奴隶军刺客', '典狱长'], locations: ['监狱二楼典狱长房'], relatedFragments: ['F11'],
    tags: ['王城混乱', '奴隶军'], narrativeText: '一份敌方文件称，奴隶军刺客已潜入城中。',
  },
]
